name: Deploy built app to production branch.

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Setup
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: npm install and build
      run: |
        npm install
        npm run build
    
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: https://github.com/LaloBenitez/lalobenitez-portfolio-production.git
        BRANCH: production
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        
